language: ruby
cache:
  bundler: true
  directories:
  - node_modules 
before_install:
- "./Scripts/dependences.sh"
script:
- "travis_wait 30 sh ./Scripts/build.sh"
after_success:
- "./Scripts/deploy.sh"
