before_install:
- chmod +x ./scripts/dependences.sh
- chmod +x ./scripts/build.sh
- chmod +x ./scripts/deploy.sh
- "./scripts/dependences.sh"
script:
- "travis_wait 30 sh ./scripts/build.sh"
after_success:
- "./scripts/deploy.sh"
